// Linear Diophantine equation: given integers a, b, c, find
// integer solutions (x, y) to  a·x + b·y = c.
//
// Bezout's identity: a·x + b·y = gcd(a, b) is always solvable, and
// the *extended* Euclidean algorithm produces one such (x₀, y₀).
// Then a·x + b·y = c is solvable iff gcd(a, b) divides c, in which
// case a particular solution is
//
//   x = x₀ · (c / g),  y = y₀ · (c / g)
//
// and *all* solutions are generated by shifting along the null
// direction: (x + k·b/g,  y − k·a/g) for any integer k. That
// infinite family is important — e.g. the "coin problem" or
// "make change with two denominations" hinges on picking the
// solution with both x, y ≥ 0.
//
// Uses: RSA key generation, chinese_remainder theorem, computing
// modular inverses (see number_theory/modular_inverse.dart), and
// the classical Frobenius / chicken McNugget problem. See
// number_theory/extended_euclidean.dart for the underlying tool.
class _ExtGcd { final int g, x, y; const _ExtGcd(this.g, this.x, this.y); }

_ExtGcd _extGcd(int a, int b) {
  if (b == 0) return _ExtGcd(a, 1, 0);
  final r = _extGcd(b, a % b);
  return _ExtGcd(r.g, r.y, r.x - (a ~/ b) * r.y);
}

class DiophantineSolution {
  final int x0, y0;
  final int stepX, stepY;
  const DiophantineSolution(this.x0, this.y0, this.stepX, this.stepY);
  ({int x, int y}) at(int k) => (x: x0 + k * stepX, y: y0 + k * stepY);
}

DiophantineSolution? solveDiophantine(int a, int b, int c) {
  if (a == 0 && b == 0) return c == 0 ? const DiophantineSolution(0, 0, 0, 0) : null;
  final r = _extGcd(a.abs(), b.abs());
  if (c % r.g != 0) return null;
  final scale = c ~/ r.g;
  final x0 = r.x * scale * (a < 0 ? -1 : 1);
  final y0 = r.y * scale * (b < 0 ? -1 : 1);
  return DiophantineSolution(x0, y0, b ~/ r.g, -(a ~/ r.g));
}

void main() {
  final s = solveDiophantine(3, 6, 9)!;                 // gcd=3, 9 mod 3=0 → solvable
  print('particular: x=${s.x0}, y=${s.y0}');
  print('at k=1     : ${s.at(1)}');
  print('at k=-1    : ${s.at(-1)}');
  print(solveDiophantine(3, 6, 8));                     // null — 8 mod 3 ≠ 0
  print(solveDiophantine(25, 15, 100)!.x0);             // some x
}
